export const AuditAction = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",
  USER_MANAGER_CHANGED: "USER_MANAGER_CHANGED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",

  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_DELETED: "ROLE_DELETED",
  ROLE_STATUS_CHANGED: "ROLE_STATUS_CHANGED",
  ROLE_PERMISSIONS_CHANGED: "ROLE_PERMISSIONS_CHANGED",

  GROUP_CREATED: "GROUP_CREATED",
  GROUP_UPDATED: "GROUP_UPDATED",
  GROUP_DELETED: "GROUP_DELETED",
  GROUP_STATUS_CHANGED: "GROUP_STATUS_CHANGED",
  GROUP_PERMISSIONS_CHANGED: "GROUP_PERMISSIONS_CHANGED",

  PERMISSION_CREATED: "PERMISSION_CREATED",
  PERMISSION_UPDATED: "PERMISSION_UPDATED",
  PERMISSION_DELETED: "PERMISSION_DELETED",
} as const;

export type AuditAction =
  (typeof AuditAction)[keyof typeof AuditAction];